---
- name: Create In Memory Inventory Group Based on CMDB
  hosts: localhost

  tasks:
   
    - ansible.builtin.debug: var=cmdb_sys_id

    - name: Lookup CI name from sys_id
      servicenow.itsm.configuration_item_info:
        sys_id: "{{ cmdb_sys_id }}"
      register: ci_info

    - ansible.builtin.debug: 
          msg: "{{ ci_info.records[0].name }}"

    - name: Set dynamic target host
      ansible.builtin.set_fact:
            target_host: "{{ ci_info.records[0].name | lower }}"
       
    
