---
- name: Deploy VM
  hosts: localhost
  vars_files:
     - vars/sizing.yml
  tasks:

    - name: Pip install depedencies for servicenow.snow_record. TODO , create execution environment
      ansible.buitin.pip:
         name: 
            - pysnow
            - requests

    - name: Deploy {{ vm_provider }}
      ansible.builtin.debug:
         msg: 
            - "Calling {{ vm_provider }} VM Deploy with these parameters"
            - "Hostname --> {{ vm_hostname }}"
            - "Size --> {{ vm_size }}"
            - "Number of CPU --> {{ tshirt_sizes[vm_size].cpu}}"
            - "Memory --> {{ tshirt_sizes[vm_size].ram_gb}}"
            - "Storage --> {{ tshirt_sizes[vm_size].storage_gb}}"
            - "SNOW REQ ID --> {{ snow_request_item_number }}"

    
     # - name: Create VM on Nutanix
    #   nutanix.nutanix.nutanix_vm:
    #     prism_host: "{{ nutanix_host }}"
    #     prism_user: "{{ nutanix_username }}"
    #     prism_password: "{{ nutanix_password }}"
    #     validate_certs: false
    #     state: present
    #     name: "{{ vm_name }}"
    #     cluster: "{{ cluster_name }}"
    #     num_vcpus: "{{ tshirt_sizes[size].cpu }}"
    #     num_cores_per_vcpu: 1
    #     memory_gb: "{{ tshirt_sizes[size].ram_gb }}"
    #     nics:
    #       - network: "{{ network_name }}"
    #     disks:
    #       - size_gb: "{{ tshirt_sizes[size].storage_gb }}"
    #         type: "DISK"
    #         bus: "SCSI"
    #     power_state: "on"
    #   register: vm_result
    #   when: vm_provider is 'nutanix'


    - name: Post-Provisioning Block
      block:
        - name: Calling VM Provisioning Role
          ansible.builtin.debug:
            msg: "..... Provisioning Complete"

        - name: Set Provisioning Success Flag to true
          ansible.builtin.set_fact:
            vm_provisioning_success: true

    
    - name: Post a worknote and a comment on ticket# {{ snow_request_item_number }} when success
      servicenow.servicenow.snow_record:
        display_value: true
        number: "{{ snow_request_item_number }}"
        state: present
        table: sc_req_item
        data:
          work_notes: "This worknote has been introduced by Ansible"
          comments: "This has been provisioned using Ansible Autmation"
          state: "Closed Completed"
      when: vm_provisioning_success == true

