---
- name: Deploy Nutanix
  hosts: localhost
  vars_files:
     - vars/sizing.yml
  tasks:



    - name: Deploy {{ vm_provider }}
      ansible.builtin.debug:
         msg: 
            - "Calling {{ vm_provider }} VM Deploy with these parameters"
            - "Hostname --> {{ vm_hostname }}"
            - "Size --> {{ vm_size }}"
            - "Number of CPU --> {{ tshirt_sizes[vm_size].cpu}}"
            - "Memory --> {{ tshirt_sizes[vm_size].ram_gb}}"
            - "Storage --> {{ tshirt_sizes[vm_size].storage_gb}}"
            - "SNOW REQ ID --> {{ snow_req_id }}"



    # - name: Create VM on Nutanix
    #   nutanix.nutanix.nutanix_vm:
    #     prism_host: "{{ nutanix_host }}"
    #     prism_user: "{{ nutanix_username }}"
    #     prism_password: "{{ nutanix_password }}"
    #     validate_certs: false
    #     state: present
    #     name: "{{ vm_name }}"
    #     cluster: "{{ cluster_name }}"
    #     num_vcpus: "{{ tshirt_sizes[size].cpu }}"
    #     num_cores_per_vcpu: 1
    #     memory_gb: "{{ tshirt_sizes[size].ram_gb }}"
    #     nics:
    #       - network: "{{ network_name }}"
    #     disks:
    #       - size_gb: "{{ tshirt_sizes[size].storage_gb }}"
    #         type: "DISK"
    #         bus: "SCSI"
    #     power_state: "on"
    #   register: vm_result

    # - name: Show VM deployment result
    #   debug:
    #     var: vm_result