---
- name: Remediate SNOW Demo - Stop plexmediaserver service
  hosts: "{{ target_host }}"
  vars:
     target_service: plexmediaserver
  become: true
  tasks:
    - name: Stop target service
      ansible.builtin.service:
        name: "{{ target_service }}"
        state: stopped
     
    - name: Confirm service stopped
      ansible.builtin.shell: systemctl is-active {{ target_service }}
      register: status
      failed_when: false

    - ansible.builtin.debug: var=cr_number
    

    # - name: Close change_request
    #   servicenow.itsm.change_request:
    #    state: closed
    #    close_code: "successful"
    #    close_notes: "Closed"
    #    number: CHG0000001
