- name: Remediate SNOW Demo - Stop plexmediaserver service
  hosts: '{{ cmdb_host }}'
  
  tasks:

    - name: Lookup CI name from sys_id
      servicenow.itsm.configuration_item_info:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
          validate_certs: false
        sys_id: "{{ cmdb_sys_id }}"
      register: ci_info


    - ansible.builtin.debug: var=ci_info
  
