- name: Update ServiceNow
  hosts: localhost
  gather_facts: false

  vars:
    aap_url: "https://aap24.dthong.com"
    snow_username: "{{ lookup('env', 'SN_USERNAME') }}"
    snow_password: "{{ lookup('env', 'SN_PASSWORD') }}"
    snow_host: "{{ lookup('env', 'SN_HOST') }}"

  tasks:
    - name: Call Role to Generate Work Notes
      ansible.builtin.include_role:
        name: generate_work_notes

    - name: Call ServiceNow Role to Close CTASK
      ansible.builtin.include_role:
        name: servicenow_change_request
        vars:
          servicenow_cr: "close_ctask"
          change_request_number: "{{ snow_change_request_number }}"
          ctask_close_code: "successful"
          ctask_close_notes: "Closed with AAP job # {{ tower_job_id }}"
          ctask_worknotes: "{{ rendered_notes.content }}"
          ctask_description: "{{ ctask_description }}"
      when:
        - snow_change_request_number is defined
        - snow_action == "close_ctask"

    - name: Call ServiceNow Role to Cancel CTASK
      ansible.builtin.include_role:
        name: servicenow_change_request
      vars:
        servicenow_cr: "canceled_ctask"
        change_request_number: "{{ snow_change_request_number }}"
        ctask_worknotes: "{{ rendered_notes.content }}"
        ctask_description: "{{ ctask_description }}"
      when:
        - snow_change_request_number is defined
        - snow_action == "canceled_ctask"

    - name: Call ServiceNow Role to Update RITM
      ansible.builtin.include_role:
        name: servicenow_ritm
      vars:
        servicenow_ritm: "update_ritm"
        snow_request_item_number: "{{ snow_request_item_number }}"
        ritm_work_notes: "{{ rendered_notes.content }}"
        ritm_comments: "This has been provisioned using Ansible Automation"
      when:
        - snow_request_item_number is defined
        - snow_action == "update_ritm"
