---
- name: Validate Deployment of VM
  hosts: localhost
  vars_files:
    - vars/sizing.yml
    - vars/defaults.yml
  vars:
    aap_job_id: "{{ tower_job_id }}"
    aap_job_url: "https://{{ aap_controller_hostname }}/#/jobs/playbook/{{ tower_job_id }}/output"
    validation_ctask_description: Automation Validation
  tasks:
    - name: Validate Deployment for  {{ vm_provider }}
      ansible.builtin.debug:
        msg:
          - "Validating {{ vm_provider }} VM Deploy with these parameters"
          - "Hostname --> {{ vm_hostname }}"
          - "Size --> {{ vm_size }}"
          - "Number of CPU --> {{ tshirt_sizes[vm_size].cpu}}"
          - "Memory --> {{ tshirt_sizes[vm_size].ram_gb}}"
          - "Storage --> {{ tshirt_sizes[vm_size].storage_gb}}"
          - "SNOW REQ ID --> {{ snow_request_item_number }}"
          - "SNOW CHANGE RQUEST NUMBER --> {{ change_request_number }} "
            
    # Block of tasks or role to validate VM provisioning
    - name: Provisioning Validation Block
      block:
        # Perform all provisioning validation tasks
        # If all provisioning validation tasks are executed without error set vm_validation_success to trye
        # and update change request CTask
        - name: Set Provisioning Validation Success Flag to true
          ansible.builtin.set_fact:
            vm_validation_success: true

        - name: Call ServiceNow Role to Close CTASK
          ansible.builtin.include_role:
            name: servicenow_change_request
          vare:
            servicenow_cr: "close_ctask"
            change_request_number: "{{ change_request_number }}"
            ctask_close_code: "successful"
            ctask_close_notes: "Closed with AAP job # {{ tower_job_id }}"
            ctask_worknotes: "Validation Automated by AAP job ID: {{ tower_job_id }}"
            ctask_description: "{{ validation_ctask_description }}"
      rescue:
        - name: Set Provisioning Validation Success Flag to false
          ansible.builtin.set_fact:
            vm_validation_success: false
        - name: Log failure message
          ansible.builtin.debug:
            msg: "Provisioning Validation failed — invoking error handling role."
        - name: Call the error handling role
          ansible.builtin.include_role:
            name: error_handling
          vars:
            error_context: "Validation Block failed."
            change_request_number: "{{ change_request_number }}"
        - name: Call ServiceNow Role to Cancel CTASK
          ansible.builtin.include_role:
            name: servicenow_change_request
          vars:
            servicenow_cr: "canceled_ctask"
            change_request_number: "{{ change_request_number }}"
            ctask_worknotes: "Validation of Automated Provisioning Failed. Automated Provisioning Validation performed by AAP job ID: {{ tower_job_id }}. 
            The output of the AAP job can be seen at {{ aap_job_url }}"
            ctask_description: "{{ validation_ctask_description }}"
      always:
        - name: Show final provisioning validation result
          ansible.builtin.debug:
            msg: "Provisioning Validation success: {{ vm_validation_success | default(false) }}"

        # Thinking RITM work notes and etc should be updated only after validation has succeeded.
        - name: Call ServiceNow Role to Update RITM
          ansible.builtin.include_role:
            name: servicenow_ritm
          vars:
            servicenow_ritm: "update"
            snow_request_item_number: "{{ snow_request_item_number }}"
            ritm_work_notes: "Provisioning complete. View job: [AAP Job #{{ aap_job_id }}]({{ aap_job_url }})"
            ritm_comments: "This has been provisioned using Ansible Automation"
          when: vm_validation_success == true

