---
- name: Retrieve sys_id for RITM {{ snow_request_item_number }}
  servicenow.itsm.api_info:
    resource: sc_req_item
    sysparm_query: "number={{ snow_request_item_number }}"
    display_value: "true"
    exclude_reference_link: true
    columns:
      - state
      - number
      - sys_id
    query_no_domain: true
    no_count: false
  register: ritm_info
  delegate_to: localhost
