---
- name: Cancel Change Request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_host }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
    state: canceled
    number: "{{ change_request_number }}"
  delegate_to: localhost
