---
- name: Close Change Request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_host }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
    state: closed
    number: "{{ change_request_number }}"
    close_code: "{{ cr_close_code }}"
    close_notes: "{{ cr_close_notes }}"
    other:
      work_notes: "{{ cr_work_notes }}"
  delegate_to: localhost

