---
- name: ServiceNow Scheduled Change Handler
  hosts: all

  sources:
    - name: Watch for scheduled change requests post approval
      servicenow.itsm.records:
        instance:
          host: https://ven05427.service-now.com
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
          validate_certs: false
        table: change_request
        interval: 10
        sysparm_query: "state=-2"
        updated_since: "2025-10-08 00:00:00"

  rules:
    - name: Launch AAP job when scheduled change detected
      condition: event.state is defined and event.state == "-2"
      action:
        run_job_template:
          name: "Remediate SNOW Demo"
          organization: "Default"
          job_args:
            extra_vars:
              cmdb_host: "{{ event.cmdb_ci | default('plexserver.lan') }}"
              change_number: "{{ event.number }}"
              description: "{{ event.short_description | default('No description') }}"

    # - name: Debug incoming change request event
    #   condition: event is defined
    #   action:
    #     debug:
    #       var: event
