---
- name: ServiceNow Incident Poller - NEW + Contains "test"
  hosts: all

  sources:
    - name: Poll NEW incidents containing "test"
      servicenow.itsm.records:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
          validate_certs: false
        table: incident
        interval: 10
        sysparm_query: "state=1^short_descriptionLIKEtest"

  rules:
    - name: Launch workflow when NEW incident matches filter
      condition: event.state is defined
      actions:

        - debug:
            msg: >
              DetectionLatencySeconds={{ (__import__('datetime').datetime.fromisoformat(event.meta.received_at.replace('Z','+00:00')) - __import__('datetime').datetime.strptime(event.sys_updated_on, "%Y-%m-%d %H:%M:%S")).total_seconds() }}
              SNOW_UpdatedAt={{ event.sys_updated_on }}
              EDA_ReceivedAt={{ event.meta.received_at }}

        - run_workflow_template:
            name: "SNOW Remediation Demo - Workflow To Stop Service"
            organization: "Default"
            job_args:
              extra_vars:
                incident_number: "{{ event.number }}"
                incident_sys_id: "{{ event.sys_id }}"
                cmdb_sys_id: "{{ event.cmdb_ci }}"
                short_description: "{{ event.short_description }}"
