---
- name: ServiceNow Scheduled Change Handler
  hosts: all

  sources:
    - name: Watch for scheduled change requests post approval
      servicenow.itsm.records:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
          validate_certs: false
        table: change_request
        interval: 10
        sysparm_query: "state=-2"
        updated_since: "2025-10-08 00:00:00"
        custom_headers:
          sysparm_display_value: true  # returns display_name fields like “Scheduled”

  rules:
    - name: Launch AAP job when scheduled change detected
      condition: event.state is defined and event.state == "-2"
      action:
        run_workflow_template:
          name: "SNOW Remediation Demo - Workflow To Stop Service"
          organization: "Default"
          job_args:
            extra_vars:
              cmdb_sys_id: "{{ event.cmdb_ci }}"
              ch_request_id: "{{ event.number }}"
              target_host: ""
