---
# tasks file for error_handling

- name: Delete VM from Nutanix (example)
  nutanix.nutanix.nutanix_vm:
    prism_hostname: "{{ nutanix_host }}"
    prism_username: "{{ nutanix_user }}"
    prism_password: "{{ nutanix_pass }}"
    validate_certs: false
    state: absent
    vm_name: "{{ vm_name }}"
  register: vm_delete_result
  ignore_errors: true

- name: Log deletion result
  ansible.builtin.debug:
    msg: "VM deletion result: {{ vm_delete_result }}"

  # refer to : https://docs.ansible.com/ansible/latest/collections/infoblox/nios_modules/nios_fixed_address_module.html
- name: Release IP address from Infoblox
  infoblox.nios_modules.nios_fixed_address:
    host: "{{ infoblox_host }}"
    username: "{{ infoblox_username }}"
    password: "{{ infoblox_password }}"
    network: "192.168.0.0/24"
    ipaddr: "{{ vm_ip }}"
    state: absent
    validate_certs: false
  delegate_to: localhost
  register: release_result

- name: Failed Provisioning Block
  block:
    - name: Cancel Automation Provisioning CTask
      servicenow.itsm.change_request_task:
        state: canceled
        number: "{{ provision_ctask_number }}"
        other:
          work_notes: "Automated Provisioning Failed. 
          Automated Provisioning performed by AAP job ID: {{ tower_job_id }}.
          The output of the AAP job can be seen at {{ aap_job_url }}"
      when: provision_ctask_number is defined

     # Should the change request be closed or moved to review when CTask fails?
    - name: Close change_request
      servicenow.itsm.change_request:
        instance:
          host: https://instance_id.service-now.com
          username: user
          password: pass

        state: closed
        close_code: "unsuccessful"
        close_notes: "{{ provision_ctask_description }} CTASK failed"
        number: "{{ change_request_number }}"
        other:
          work_notes: "More details of why the change request is being closed.
          Maybe list of failed APP tasks or the log output itself."

    - name: debug Automation Provisioning CTask
      ansible.builtin.debug:
        var: ctask_provision
  when: failed_stage == "provisioning"


- name: Failed Validation Block
  block:
    - name: Cancel Automation Provisioning Validation CTask
      servicenow.itsm.change_request_task:
        state: canceled
        number: "{{ validation_ctask_number }}"
        other:
          work_notes: "Automated Provisioning Validation Failed. 
          Automated Provisioning Validation performed by AAP job ID: {{ tower_job_id }}.
          The output of the AAP job can be seen at {{ aap_job_url }}"
      when: validation_ctask_number is defined

    # Should the change request be closed or moved to review when CTask fails?
    - name: Close change_request
      servicenow.itsm.change_request:
        instance:
          host: https://instance_id.service-now.com
          username: user
          password: pass

        state: closed
        close_code: "unsuccessful"
        close_notes: "{{ validation_ctask_description }} CTASK failed"
        number: "{{ change_request_number }}"
        other:
          work_notes: "More details of why the change request is being closed.
          Maybe list of failed APP tasks or the log output itself."


    - name: debug Automation Provisioning Validation CTask
      ansible.builtin.debug:
        var: ctask_validation
  when: failed_stage == "validation"
