- name: Create the VM
  ansible.builtin.include_tasks: vm_provision_nutanix_create_vm.yml
  
- name: Join Satellite
  ansible.builtin.include_tasks: vm_provision_nutanix_create_host_entry_satellite.yml

- name: ISO image and OS Build
  ansible.builtin.include_tasks: vm_provision_nutanix_iso_os_build.yml

- name: Update Inventory in AAP
  ansible.builtin.include_tasks: vm_provision_nutanix_update_inventory.yml

- name: Enable SSH and cleanup
  ansible.builtin.include_tasks: vm_provision_nutanix_ssh_cleanup.yml

